### ISSUE TITLE
download folders

### ISSUE THREAD

**Issue by shahdiyor** [Pterko/yandex-disk-client#4]
hello, alexey! I have a question, is it possible to download folders with files using your code? If so, tell me how, I will be grateful.

**Comment by Pterko** [comment]
Hi! What do you mean by "download folders"? 
Currently, you have an option to receive a listing of files in a directory through `getFolderResources` method, and after that use `getFileDownloadUrl` for all files in this folder.
Or you want to receive a zip archive with all content of the specified folder? In this case, you can try to use `getFileDownloadUrl` with the folder's path, it may work. If not, tell me, I'll try this by myself.

**Comment by shahdiyor** [comment]
First of all, thank you for answering. By "download folders", I mean
download all files from the folder.

ср, 16 дек. 2020 г., 21:29 Alexey Kolchanov <notifications@github.com>:

**Comment by Pterko** [comment]
Then you may go with the way, that I've described before. I don't think that I need to implement downloading in my module, getting an URL should be efficient.
Also, as far as I know, there is no way to get download links for files in "bulk", so any way you will need to iterate through the content of a folder.

**Comment by shahdiyor** [comment]
Understood you, thank you very much!
